name: Upload Stargate Teleporter

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python (for gdown)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install gdown
        run: pip install gdown

      - name: Download ZIP via gdown
        run: |
          gdown https://drive.google.com/uc?id=1A2B3C4D5E6F7G8H9 -O ArkReactors_Teleporter.zip

      - name: Unzip package
        run: unzip -o ArkReactors_Teleporter.zip -d .

      - name: Commit new files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add \
            ArkReactors_Teleporter.fbx \
            ArkReactors_Teleporter.stl \
            ArkReactors_Teleporter.uasset \
            Materials/ \
            README_SETUP_GUIDE.txt
          git commit -m "Add cinematic Stargate teleporter package" || echo "No changes to commit"
          git push

