name: Upload Stargate Teleporter

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download ZIP
        run: |
          wget -O ArkReactors_Teleporter.zip \
            "https://drive.google.com/uc?export=download&id=1A2B3C4D5E6F7G8H9"

      - name: Unzip package
        run: unzip -o ArkReactors_Teleporter.zip -d .

      - name: Commit new files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ArkReactors_Teleporter.fbx \
                  ArkReactors_Teleporter.stl \
                  ArkReactors_Teleporter.uasset \
                  Materials/ \
                  README_SETUP_GUIDE.txt
          git commit -m "Add cinematic Stargate teleporter package" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
